
export const  SET_API_URL = 'SET_API_URL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const FAILURE_REFRESH_TOKEN = 'FAILURE_REFRESH_TOKEN';
export const RESTORE_LOGIN = 'RESTORE_LOGIN';

export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST';
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS';
export const SCHEDULE_FAILURE = 'SCHEDULE_FAILURE';

export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';

export const PATIENT_GALLERY_REQUEST = 'PATIENT_GALLERY_REQUEST';
export const PATIENT_GALLERY_SUCCESS = 'PATIENT_GALLERY_SUCCESS';
export const PATIENT_GALLERY_FAILURE = 'PATIENT_GALLERY_FAILURE';

export const GET_HTML_REQUEST = 'GET_HTML_REQUEST';
export const GET_HTML_FAILURE = 'GET_HTML_FAILURE';
export const GET_HTML_SUCCESS = 'GET_HTML_SUCCESS';

export const DOCTORSSCHEDULE_SORT = 'DOCTORSSCHEDULE_SORT';
export const OPEN_PATIENT = 'OPEN_PATIENT';

export const SET_FILD = 'SET_FILD';
export const ADD_PHOTO = 'ADD_PHOTO';
export const REMOVE_PHOTO = 'REMOVE_PHOTO';

export const OPEN_SERVICE = 'OPEN_SERVICE';
export const SERVICE_DATA_REQUEST = 'SERVICE_DATA_REQUEST';
export const SERVICE_DATA_SUCCESS = 'SERVICE_DATA_SUCCESS';
export const SERVICE_DATA_FAILURE = 'SERVICE_DATA_FAILURE';

export const DOWNLOAD_EDIPHOTO_REQUEST = 'DOWNLOAD_EDIPHOTO_REQUEST';
export const DOWNLOAD_EDIPHOTO_FAILURE = 'DOWNLOAD_EDIPHOTO_FAILURE';
export const DOWNLOAD_EDIPHOTO_SUCCESS = 'DOWNLOAD_EDIPHOTO_SUCCESS';

export const SAVE_COMENT_REQUEST = 'SAVE_COMENT_REQUEST';
export const SAVE_COMENT_SUCCESS = 'SAVE_COMENT_SUCCESS';
export const SAVE_COMENT_FAILURE = 'SAVE_COMENT_FAILURE';

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_FAILURE = 'DELETE_PHOTO_FAILURE';

export const GET_LIST_PATIENTS_REQUEST = 'GET_LIST_PATIENTS_REQUEST';
export const GET_LIST_PATIENTS_FAILURE = 'GET_LIST_PATIENTS_FAILURE';
export const GET_LIST_PATIENTS_SUCCESS = 'GET_LIST_PATIENTS_SUCCESS';
export const SET_SEARCHTEXT_PATIENTS = 'SET_SEARCHTEXT_PATIENTS';

export const SAVE_VALUE_PARAMETR_REQUEST = 'SAVE_VALUE_PARAMETR_REQUEST';
export const SAVE_VALUE_PARAMETR_SUCCESS = 'SAVE_VALUE_PARAMETR_SUCCESS';
export const SAVE_VALUE_PARAMETR_FAILURE = 'SAVE_VALUE_PARAMETR_FAILURE';


